- name: Configure webserver ningx
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    conf_file: /etc/nginx/sites-available/defailt
  tasks:
    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/nginx.conf dest={{ conf_file }}

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: cpty index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted

